version: "3"

services:
  sonarqube:
    container_name: sonar-docker
    image: sonarqube:lts-community
    depends_on:
      - postgresql
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresql:5432/sonardb
      SONAR_JDBC_USERNAME: sonaruser
      SONAR_JDBC_PASSWORD: sonarpass
    volumes:
      - /home/sidik/sonar/data:/opt/sonarqube/data
      - /home/sidik/sonar/extensions:/opt/sonarqube/extensions
      - /home/sidik/sonar/logs:/opt/sonarqube/logs
    ports:
      - 9000:9000
      - 9092:9092
    networks:
      - sonar-networks

  postgresql:
    container_name: postgre-docker
    image: postgres:12
    environment:
      POSTGRES_USER: sonaruser
      POSTGRES_PASSWORD: sonarpass
      POSTGRES_DB: sonardb
    volumes:
      - /home/sidik/postgre/postgresql:/var/lib/postgresql
      - /home/sidik/postgre/data:/var/lib/postgresql/data
    networks:
      - sonar-networks

networks:
  sonar-networks:
    name: sonar-networks